DeepLinkSDK/RouteMatcher/DPLRouteMatcher.m, DeepLinkSDK/Router/DPLDeepLinkRouter.m, README.md, SampleApps/ReceiverDemo/DPLReceiverAppDelegate.m, Tests/RouteMatcher/DPLRouteMatcherSpec.m, Tests/Router/DPLDeepLinkRouterSpec.m
Allow routes to be filtered by hosts, or allow a route to match only a host value.
For example 'twitter://timeline' would be matched with a route of '[timeline]'
http://wiki.akosma.com/IPhone_URL_Schemes#Twitter
=> Allow routes to be filtered by hosts

DeepLinkSDK/RouteMatcher/DPLRouteMatcher.m, Tests/RouteMatcher/DPLRouteMatcherSpec.m
- Full regex support
- Existing functionality migrated to regex
- Wildcard routes supported with `@".*"`
=> Add regex support to DPLRouteMatcher

DeepLinkSDK/DeepLink/DPLDeepLink.h, DeepLinkSDK/DeepLink/DPLDeepLink.m, SampleApps/ReceiverDemo/DPLReceiverAppDelegate.m
I'm working on integrating `ios-deeplink-sdk` into an app that uses many links.
I find my code cluttered with `link.routeParameters[@"something"]` and `link.queryParameters[@"something"]`.
I added object subscripting to my local fork to make this code more expressive. Perhaps you'll enjoy it in your project.
This allows, for example:
self.router[@"/say/:title/:message"] = ^(DPLDeepLink *link) {
[[[UIAlertView alloc] initWithTitle:link[@"title"]
message:link[@"message"]
delegate:nil
cancelButtonTitle:NSLocalizedString(@"OK", nil)
otherButtonTitles:nil] show];
};
=> Add Object Subscripting to links

DeepLinkSDK/Router/DPLDeepLinkRouter.h, DeepLinkSDK/Router/DPLDeepLinkRouter.m, SampleApps/ReceiverDemo/DPLReceiverAppDelegate.m, Tests/Router/DPLDeepLinkRouterSpec.m
This allow us to inform the application accurately about whether we have handled the URL, rather than always returning YES regardless of the result.
=> Should returns boolean when handling URL.

.slather.yml, .travis.yml, DeepLinkSDK.xcodeproj/project.pbxproj, Gemfile, Gemfile.lock, Podfile, Podfile.lock, README.md
- Modify project file to generate code coverage metrics
- Add step to .travis.yml to install slather and send metrics to Coveralls
- Add .slather.yml to configure how metrics are sent to Coveralls 
- Update Podfile.lock to `0.36.4`
Coveralls will need to enabled for usebutton/ios-deeplink-sdk. It's already enabled for dasmer/ios-deeplink-sdk, and shows a coverage of 90%.
[![Coverage Status](https://coveralls.io/repos/dasmer/ios-deeplink-sdk/badge.svg?branch=master)](https://coveralls.io/r/dasmer/ios-deeplink-sdk?branch=master)
=> Add slather/Coveralls test coverage reports

DeepLinkSDK.xcodeproj/project.pbxproj, Podfile, Podfile.lock, SampleApps/ReceiverDemo/DPLReceiverAppDelegate.m, Tests/IntegrationTests/DPLRouteHandlerIntegrationTest.m
- Adds KIF to test the Class Based Route-Handler flow. It also increases test coverage to 95%.
[![Coverage Status](https://coveralls.io/repos/dasmer/ios-deeplink-sdk/badge.svg?branch=master)](https://coveralls.io/r/dasmer/ios-deeplink-sdk?branch=master)
=> Add KIF to test Class Based Route-Handler. Bumps Test Coverage

DeepLinkKit/Router/DPLDeepLinkRouter.h
It looks like the documentation didn't get the renaming. Fixes #64
=> Update the documentation to match DPLRouteHandler

DeepLinkKit.xcodeproj/project.pbxproj, Podfile, SampleApps/ReceiverDemo/Base.lproj/Main.storyboard, SampleApps/ReceiverDemo/SupportingFiles/ReceiverDemo-Info.plist, SampleApps/ReceiverDemoSwift/DPLReceiverSwiftAppDelegate.swift, SampleApps/ReceiverDemoSwift/Info.plist, SampleApps/ReceiverDemoSwift/ReceiverDemoSwift-Bridging-Header.h, SampleApps/ReceiverDemoSwift/RouteHandlers/DPLMessageRouteHandler.swift, SampleApps/ReceiverDemoSwift/RouteHandlers/DPLProductRouteHandler.swift
I've created a simple example of how to use the DeepLinkKit in Swift. As of creating this PR, the only way to handle routes is by creating classes that subclasses the `DPLRouteHandler`class. This was requested in #65.
In order to support the shorthand approach of registering a `DPLRouteHandlerBlock` to a route, we'd need (I believe) to enhance the library a bit more (create a sort of class/struct that has the `DPLRouteHandlerBlock` as a property would be a potential solution). This is out of scope of this PR as per #28.
I can also create a Swift version of the SenderDemo; however, there aren't many changes involved with that one. Let me know what you guys think!
=> Add a Swift Receiver Demo

README.md
The integration guide link returns a 404 - http://www.usebutton.com/sdk/deep-links/integration-guide
This commit updates the link to - https://www.usebutton.com/developers/deep-links/
=> Correct hosted documentation link.

DeepLinkKit.xcodeproj/project.pbxproj, DeepLinkKit/Categories/NSString+DPLQuery.m, Tests/Categories/NSString_DPLQuerySpec.m, Tests/DeepLink/DPLDeepLinkSpec.m, Tests/DeepLink/DPLMutableDeepLinkSpec.m
**Depends on #72**
Technically keys missing values in a query string are legit ([rfc3986](http://tools.ietf.org/html/rfc3986#section-3.4)) and we prefer when a url is parsed into a `DPLDeepLink` it is serialized into the same url.
Additionally note that `NSURL` interprets and preserves query data that is not complete key value pairs.
For example:
```objc
NSURL *url = [NSURL URLWithString:@"http://example.com?foo"];
NSLog(@"%@", url.query);
//logs the following
> foo
```
Currently DeepLinkKit will discard `foo` in this situation. This change set preserves the value as a key in `-[DPLDeepLink queryParameters]` with a placeholder value. Upon serialization, the key is placed back in the query of the URL with no value.
e.g. The query parameters of the url `http://example.com?foo&bar=baz` is …
=> Preserve query items without a value

DeepLinkKit/Router/DPLDeepLinkRouter.m
This is #31 with conflicts resolved
=> Forward route completion handler

Tests/Categories/NSObject_DPLJSONObjectSpec.m, Tests/Categories/NSString_DPLJSONSpec.m, Tests/Categories/NSString_DPLQuerySpec.m, Tests/Categories/NSString_DPLTrimSpec.m, Tests/DeepLink/DPLDeepLinkSpec.m, Tests/DeepLink/DPLDeepLink_AppLinksSpec.m, Tests/DeepLink/DPLMutableDeepLinkSpec.m, Tests/DeepLink/DPLMutableDeepLink_AppLinksSpec.m, Tests/Regex/DPLRegularExpressionSpec.m, Tests/RouteMatcher/DPLRouteMatcherSpec.m, Tests/Router/DPLDeepLinkRouterSpec.m
As it is stated in [specta example](https://github.com/specta/specta#example), there's no need to do #include "Specta.h"
=> Removing unneeded specta includes in test specs

Tests/Categories/UINavigationController_DPLRoutingSpec.m
Continuation of PR #96 .
Missed newly created Test Spec (UINavigationController_DPLRoutingSpec.m) from yesterday's commit.
=> Removing unneeded specta includes in test specs, part 2

.travis.yml, DeepLinkKit/Router/DPLDeepLinkRouter.h, DeepLinkKit/Router/DPLDeepLinkRouter.m, Tests/Router/DPLDeepLinkRouterSpec.m
Looks like specialized Class is not interfacing with Swift and declaration for
```
- (void)registerHandlerClass:(Class <DPLRouteHandler>)handlerClass forRoute:(NSString *)route;
```
can't be generated.
=> #111 - registerHandlerClass:forRoute: interface is generated for Swift 3

DeepLinkKit.podspec
This was a simple change, just adding the tvOS deployment target to the Podspec file.
=> Added tvOS support to Podspec

DeepLinkKit.podspec, DeepLinkKit.xcodeproj/project.pbxproj, DeepLinkKit.xcodeproj/xcshareddata/xcschemes/DeepLinkKit.xcscheme, DeepLinkKit/Info.plist, README.md
I'd love to be able to add Carthage support. I notice that there was a previous PR (#120) that seems to have stalled. Not sure if that is because the changes are not acceptable, or just look intimidating due to the `xcodeproj` file format.  
Anyway, this PR is slightly less large as it doesn't play with the umbrella header or the module map. I've also been very deliberate in how I've broken the commits up so you can see the specific changes that have been made along the way.  Specifically, this is what I did:
* Added a new Objective-C Cocoa Touch Framework target called `DeepLinkKit`
* When you do the above, it creates a new group in the navigator called `DeepLinkKit` with a new file called `Info.plist` and a reference to the existing `DeepLinkKit.h`. All I did was move the reference to …
=> Carthage support

DeepLinkKit.xcodeproj/project.pbxproj
The iOS deployment target for the `DeepLinkKit` build target was set to `10.3`. When added as a dependency through Carthage, this will make apps built with lower deployment target crash when running on iOS version lower than 10.3.
This PR lowers the deployment target to `7.0`, consistent with what's specified in the Podspec.
=> Lower deployment target for `DeepLinkKit` build target

DeepLinkKit.xcodeproj/project.pbxproj
When submitting builds to App Store, built with carthage and Xcode Version 11.2.1 (11B500) toolchain, I get this error in response:
> ERROR ITMS-90362: "Invalid Info.plist value. The value for the key 'MinimumOSVersion' in bundle MeetHubDev.app/Frameworks/DeepLinkKit.framework is invalid. The minimum value is 8.0"
https://github.com/button/DeepLinkKit/issues/159
This PR sets IPHONEOS_DEPLOYMENT_TARGET to 8.0, which affects the `MinimumOSVersion` plist value distributed with compiled framework.
With this update, I no longer see the App Store Connect submission error.
=> Set deployment target to 8.0 for DeepLinkKit framework target

DeepLinkKit/Info.plist
Embed Framework via Carthage results in following AppStore validation error:
Using `Carthage update --cache-builds --platform iOS` builds the framework with a default value for MinimumOSVersion of 7.0.
=> Fix AppStore Submission when used via Carthage

DeepLinkKit.xcodeproj/project.pbxproj, DeepLinkKit/Categories/NSObject+DPLJSONObject.h, DeepLinkKit/Info.plist
When builds with cocoapods and Xcode Version 12.0 (12A7209), I get this warning in response:
>  'Empty paragraph passed to '@discussion' command'
> The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99.
This PR sets IPHONEOS_DEPLOYMENT_TARGET to 9.0, which affects the MinimumOSVersion plist value distributed with compiled framework.
With this update, I no longer see the App Store Connect submission warning.
=> Fix warning on Xcode12 (Set deployment target to 9.0 for DeepLinkKit framework target)

DeepLinkKit/Categories/NSObject+DPLJSONObject.h, DeepLinkKit/DeepLink/DPLDeepLink.h, DeepLinkKit/DeepLink/DPLDeepLink.m, DeepLinkKit/DeepLink/DPLMutableDeepLink.h, DeepLinkKit/Regex/DPLMatchResult.h, DeepLinkKit/Regex/DPLRegularExpression.h, DeepLinkKit/RouteHandler/DPLRouteHandler.h, DeepLinkKit/RouteMatcher/DPLRouteMatcher.h, DeepLinkKit/Router/DPLDeepLinkRouter.h, SampleApps/ReceiverDemo/DPLReceiverAppDelegate.m, SampleApps/ReceiverDemoSwift/DPLReceiverSwiftAppDelegate.swift, SampleApps/ReceiverDemoSwift/RouteHandlers/DPLProductRouteHandler.swift
Hello
In the attached pull request I added nullability annotations for the relevant APIs, when calling objc methods from swift I really dislike not knowing for sure whether I can expect a null or not from that method.
=> Add objective c nullability annotations

DeepLinkKit/Router/DPLDeepLinkRouter.h
The nullability annotations missed the fact that this error can be null.
=> Make error nullable
